### ISSUE TITLE
Transfer repository to MicroBlocks

### ISSUE THREAD

**Issue by mrstegeman** [bromagosa/microblocks-adapter#23]
@bromagosa @kgiori I feel like this should be owned by one of you. Do either of you have any interest in having me transfer the repo to you?

**Comment by bromagosa** [comment]
I'm the one maintaining it so I guess it should be assigned to me :)

**Comment by mrstegeman** [comment]
It will be transferring from the mozilla-iot GitHub org to your personal account. Does that sound good?

**Comment by bromagosa** [comment]
Yup, sounds great. Thank you!

**Comment by mrstegeman** [comment]
@bromagosa you'll need to delete your fork before I can transfer.

**Comment by bromagosa** [comment]
Sorry about that. It's deleted now, you can go ahead and transfer it.

Thanks!
