### ISSUE TITLE
white space in programmed device name makes the name not editable and the device not deletable (from the dB)

### ISSUE THREAD

**Issue by kgiori** [bromagosa/microblocks-adapter#9]
Program a board with name "my thing" or anything with a space.
When you try to edit the name after adding it to the gateway, it will fail with an error message. 
When you try to delete the device after adding it to the gateway, it won't delete it and it won't go back to the main Things screen. It silently fails.

If the originally programmed name has no white space both above operations (edit/remove) seem to work fine.

**Comment by mrstegeman** [comment]
Fixed by mozilla-iot/gateway#1309
